Repository higorrluiz/Xadrez, pull requests merged in 2023-06, with the labels that each got.

#9 adiciona link do Drive ao README
  README.md
Labels: documentation

#13 mudança no roque
  classes/king.py
  main.py
Labels: bug

#14 adiciona menu principal
  assets/images/menu/background.jpg
  assets/images/menu/exit_button.jpg
  assets/images/menu/options_button.png
  assets/images/menu/play_button.png
  main.py
  menu.py
Labels: enhancement

#16 Feat/4/verify checks on king
  classes/bishop.py
  classes/board.py
  classes/king.py
  classes/knight.py
  classes/match.py
  classes/pawn.py
  classes/piece.py
  classes/queen.py
  classes/rook.py
  main.py
Labels: enhancement

#19 Adiciona tela de fim de jogo no xeque-mate
  board_helper.py
  main.py
  menu.py
Labels: enhancement

#20 Feat/10/verify draw conditions
  classes/board.py
  classes/king.py
  classes/match.py
  classes/piece.py
  importador.py
  main.py
  menu.py
Labels: enhancement

#22 Permite promoção do peão
  classes/pawn.py
  main.py
  menu.py
Labels: enhancement

#24 Feat/18/state
  assets/images/higor.jpg
  assets/images/menu/continue_button.png
  assets/state.txt
  board_helper.py
  classes/bishop.py
  classes/board.py
  classes/king.py
  classes/knight.py
  classes/match.py
  classes/pawn.py
  classes/piece.py
  classes/queen.py
  classes/rook.py
  importador.py
  main.py
  menu.py
Labels: enhancement

#25 Feature/15/ai
  ai.py
  board_helper.py
  classes/board.py
  classes/pawn.py
  evaluation.py
  main.py
Labels: enhancement

#31 Feat/11/unit tests
  .coverage
  .github/workflows/main.yml
  requirements.txt
  test/__init__.py
  test/assets/images/black bishop.png
  test/assets/images/black king.png
  test/assets/images/black knight.png
  test/assets/images/black pawn.png
  test/assets/images/black queen.png
  test/assets/images/black rook.png
  test/assets/images/menu/background.jpg
  test/assets/images/menu/continue_button.png
  test/assets/images/menu/easy_button.png
  test/assets/images/menu/exit_button.jpg
  test/assets/images/menu/hard_button.png
  test/assets/images/menu/mid_button.png
  test/assets/images/menu/options_button.png
  test/assets/images/menu/play_button.png
  test/assets/images/menu/player_v_cpu.png
  test/assets/images/menu/player_v_cpu_toggled.png
  test/assets/images/menu/player_v_player.png
  test/assets/images/white bishop.png
  test/assets/images/white king.png
  test/assets/images/white knight.png
  test/assets/images/white pawn.png
  test/assets/images/white queen.png
  test/assets/images/white rook.png
  test/assets/state.txt
  test/unit/__init__.py
  test/unit/test_bishop.py
  test/unit/test_board.py
  test/unit/test_king.py
  test/unit/test_knight.py
  test/unit/test_pawn.py
  test/unit/test_queen.py
  test/unit/test_rook.py
Labels: enhancement

#37 Hotfix/35/final fix
  README.md
  classes/board.py
  main.py
  menu.py
Labels: bug, documentation
